server:
  port: 8080
spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp


  freemarker:
    suffix: .html
    template-loader-path: classpath:/templates/,classpath:/static/,classpath:/public/